version: "3.8"

volumes:
  el_database:
  node_modules:

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  backend:
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
      - redis
    build:
      context: ./backend
    env_file:
      - .env
    # ports:
    #   - 3000:3000

  frontend:
    volumes:
      - ./frontend/src:/usr/src/frontend/src
      # - /usr/src/frontend/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    build:
      context: ./frontend
    tty: true

  nginx:
    build:
      context: ./devops/nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./devops/www/:/var/www
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - el_database:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_USER}:5432/${DB_NAME}?sslmode=disable
